version: "3"

services:
  web:
    build: .
    restart: always
    command: gunicorn --chdir /usr/src/app notifico.wsgi --bind 0.0.0.0:8000
    depends_on:
      - db
      - redis
      - mail
    environment:
      ENVIRONMENT: prod
    env_file:
      - .env
    volumes:
      - staticfiles:/usr/src/app/staticfiles/

  celery:
    build: .
    restart: always
    entrypoint: celery -A notifico worker -l INFO
    depends_on:
      - web
      - db
      - redis
    environment:
      ENVIRONMENT: prod
    env_file:
      - .env

  beat:
    build: .
    restart: always
    entrypoint: celery -A notifico beat -l INFO
    depends_on:
      - redis
    environment:
      ENVIRONMENT: prod
    env_file:
      - .env

  redis:
    image: redis
    restart: always

  db:
    image: mariadb:10.7
    restart: always
    volumes:
      - ./dockerdata/db:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: web
      MYSQL_USER: web
    env_file:
      - .env

  nginx:
    image: nginx
    restart: always
    expose:
      - 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/usr/src/app/staticfiles/
    depends_on:
      - web
    ports:
      - 8080:80

  mail:
    image: boky/postfix
    restart: always
    volumes:
      - ./dockerdata/mail/keys:/etc/opendkim/keys
    environment:
      ALLOWED_SENDER_DOMAINS: notifico.xyz
      DKIM_AUTOGENERATE: 1

volumes:
  staticfiles:
